### ISSUE TITLE
Logo Design: GamingNews

### ISSUE THREAD

**Issue by baranpirincal** [eagskunst/GamingNews#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by eagskunst** [comment]
Hi there!

Yes, I'm interested. Download the .apk version from the release tab and try it to see what combines better with a possible logo. When you're ready, please make a Pull Request so I can see it and use it.
